// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home_Scr.h"
#include "screens/ui_Color_Scr.h"
#include "screens/ui_Settings_Scr.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HideBtn_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * ShowBtn_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_monkey_png);    // assets/monkey.png
LV_IMG_DECLARE(ui_img_dog_png);    // assets/dog.png
LV_IMG_DECLARE(ui_img_lamb_png);    // assets/lamb.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
