// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#ifndef _ESP32_GUI_UI_H
#define _ESP32_GUI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void SpinAndLargen_Animation(lv_obj_t * TargetObject, int delay);
void LargeBtn_Animation(lv_obj_t * TargetObject, int delay);
void MoveColorToCenter_Animation(lv_obj_t * TargetObject, int delay);
void MoveSettingsToCenter_Animation(lv_obj_t * TargetObject, int delay);
void HideBtn_Animation(lv_obj_t * TargetObject, int delay);
void ShowBtn_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Home_Scr
void ui_Home_Scr_screen_init(void);
extern lv_obj_t * ui_Home_Scr;
void ui_event_Color_Btn_Home(lv_event_t * e);
extern lv_obj_t * ui_Color_Btn_Home;
extern lv_obj_t * ui_Colorwheel_Home;
extern lv_obj_t * ui_BL_logo_Home;
extern lv_obj_t * ui_Dark_Mode_Label;
void ui_event_Dark_Mode_Switch(lv_event_t * e);
extern lv_obj_t * ui_Dark_Mode_Switch;
void ui_event_Settings_Btn_Home(lv_event_t * e);
extern lv_obj_t * ui_Settings_Btn_Home;
extern lv_obj_t * ui_Settings_Icon_Home;
// SCREEN: ui_Color_Scr
void ui_Color_Scr_screen_init(void);
extern lv_obj_t * ui_Color_Scr;
void ui_event_Dark_Mode_Switch_Color(lv_event_t * e);
extern lv_obj_t * ui_Dark_Mode_Switch_Color;
extern lv_obj_t * ui_Dark_Mode_Label_Color;
void ui_event_Home_Btn_Color(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Color;
extern lv_obj_t * ui_Home_Img_C;
extern lv_obj_t * ui_BL_logo_Color;
extern lv_obj_t * ui_Colorwheel;
extern lv_obj_t * ui_LED_color_panel;
extern lv_obj_t * ui_LED_color_label;
// SCREEN: ui_Settings_Scr
void ui_Settings_Scr_screen_init(void);
extern lv_obj_t * ui_Settings_Scr;
void ui_event_Dark_Mode_Switch_Sett(lv_event_t * e);
extern lv_obj_t * ui_Dark_Mode_Switch_Sett;
extern lv_obj_t * ui_Dark_Mode_Label_Sett;
void ui_event_Home_Btn_Sett(lv_event_t * e);
extern lv_obj_t * ui_Home_Btn_Sett;
extern lv_obj_t * ui_Home_Img_S;
extern lv_obj_t * ui_BL_logo_Sett;
extern lv_obj_t * ui_Settings_scroll_panel;
extern lv_obj_t * ui_Checkbox_Sett;
extern lv_obj_t * ui_Dropdown_Sett;
extern lv_obj_t * ui_Roller_Sett;
extern lv_obj_t * ui_Slider1_Sett;
void ui_event_Text_area(lv_event_t * e);
extern lv_obj_t * ui_Text_area;
extern lv_obj_t * ui_Arc_Sett;
extern lv_obj_t * ui_Slider2_Sett;
void ui_event_Keyboard_Sett(lv_event_t * e);
extern lv_obj_t * ui_Keyboard_Sett;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_colorwheel_icon_png);    // assets/colorwheel_icon.png
LV_IMG_DECLARE(ui_img_bl_logo_symbol_png);    // assets/bl_logo_symbol.png
LV_IMG_DECLARE(ui_img_settings_icon_png);    // assets/settings_icon.png
LV_IMG_DECLARE(ui_img_home_icon_png);    // assets/home_icon.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
