// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "ui.h"

void dark_mode_on(lv_event_t *e)
{
}

void dark_mode_off(lv_event_t *e)
{
}

// Removed references to non-existent screens
// Available screens: ui_Home_Scr, ui_Color_Scr, ui_Settings_Scr
// The next_animal() and prev_animal() functions have been removed as they
// referenced Screen1-Screen8 which do not exist in this project.