// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef UI_COLOR_SCR_H
#define UI_COLOR_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Color_Scr
extern void ui_Color_Scr_screen_init(void);
extern void ui_Color_Scr_screen_destroy(void);
extern lv_obj_t * ui_Color_Scr;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

