// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Color_Scr = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home_Scr, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Home_Scr_screen_init);
    }
}

// build funtions

void ui_Color_Scr_screen_init(void)
{
    ui_Color_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Color_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Color_Scr, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Color_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Color_Scr);
    lv_obj_set_width(ui_Button3, 260);
    lv_obj_set_height(ui_Button3, 235);
    lv_obj_set_x(ui_Button3, -1);
    lv_obj_set_y(ui_Button3, -5);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button3, &ui_img_dog_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Color_Scr_screen_destroy(void)
{
    if(ui_Color_Scr) lv_obj_del(ui_Color_Scr);

    // NULL screen variables
    ui_Color_Scr = NULL;
    ui_Button3 = NULL;

}
