// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: esp32_gui

#ifndef UI_SETTINGS_SCR_H
#define UI_SETTINGS_SCR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings_Scr
extern void ui_Settings_Scr_screen_init(void);
extern void ui_Settings_Scr_screen_destroy(void);
extern lv_obj_t * ui_Settings_Scr;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

