// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: esp32_gui

#include "../ui.h"

lv_obj_t * ui_Settings_Scr = NULL;
lv_obj_t * ui_Button4 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Color_Scr, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_Color_Scr_screen_init);
    }
}

// build funtions

void ui_Settings_Scr_screen_init(void)
{
    ui_Settings_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Button4, 321);
    lv_obj_set_height(ui_Button4, 238);
    lv_obj_set_x(ui_Button4, -1);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Button4, &ui_img_lamb_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Settings_Scr_screen_destroy(void)
{
    if(ui_Settings_Scr) lv_obj_del(ui_Settings_Scr);

    // NULL screen variables
    ui_Settings_Scr = NULL;
    ui_Button4 = NULL;

}
