// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: esp32_gui

#include "../ui.h"

void ui_Settings_Scr_screen_init(void)
{
    ui_Settings_Scr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings_Scr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_Scr, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_Scr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dark_Mode_Switch_Sett = lv_switch_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Dark_Mode_Switch_Sett, 32);
    lv_obj_set_height(ui_Dark_Mode_Switch_Sett, 15);
    lv_obj_set_x(ui_Dark_Mode_Switch_Sett, 139);
    lv_obj_set_y(ui_Dark_Mode_Switch_Sett, 107);
    lv_obj_set_align(ui_Dark_Mode_Switch_Sett, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Dark_Mode_Switch_Sett, LV_STATE_CHECKED);       /// States

    lv_obj_set_style_bg_color(ui_Dark_Mode_Switch_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Dark_Mode_Switch_Sett, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Dark_Mode_Label_Sett = lv_label_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Dark_Mode_Label_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Dark_Mode_Label_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dark_Mode_Label_Sett, 76);
    lv_obj_set_y(ui_Dark_Mode_Label_Sett, 107);
    lv_obj_set_align(ui_Dark_Mode_Label_Sett, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Dark_Mode_Label_Sett, "Dark mode");
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Dark_Mode_Label_Sett, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_Dark_Mode_Label_Sett, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Home_Btn_Sett = lv_btn_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Home_Btn_Sett, 36);
    lv_obj_set_height(ui_Home_Btn_Sett, 31);
    lv_obj_set_x(ui_Home_Btn_Sett, -133);
    lv_obj_set_y(ui_Home_Btn_Sett, 94);
    lv_obj_set_align(ui_Home_Btn_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Btn_Sett, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_Btn_Sett, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_Btn_Sett, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_Btn_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_Img_S = lv_img_create(ui_Home_Btn_Sett);
    lv_img_set_src(ui_Home_Img_S, &ui_img_home_icon_png);
    lv_obj_set_width(ui_Home_Img_S, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Home_Img_S, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Home_Img_S, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_Img_S, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Home_Img_S, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Home_Img_S, 50);

    ui_BL_logo_Sett = lv_img_create(ui_Settings_Scr);
    lv_img_set_src(ui_BL_logo_Sett, &ui_img_bl_logo_symbol_png);
    lv_obj_set_width(ui_BL_logo_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BL_logo_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BL_logo_Sett, 139);
    lv_obj_set_y(ui_BL_logo_Sett, -101);
    lv_obj_set_align(ui_BL_logo_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BL_logo_Sett, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BL_logo_Sett, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BL_logo_Sett, 50);

    ui_Settings_scroll_panel = lv_obj_create(ui_Settings_Scr);
    lv_obj_set_width(ui_Settings_scroll_panel, 304);
    lv_obj_set_height(ui_Settings_scroll_panel, 153);
    lv_obj_set_align(ui_Settings_scroll_panel, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Settings_scroll_panel, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_scroll_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings_scroll_panel, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings_scroll_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox_Sett = lv_checkbox_create(ui_Settings_scroll_panel);
    lv_checkbox_set_text(ui_Checkbox_Sett, "This is a checkbox");
    lv_obj_set_width(ui_Checkbox_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox_Sett, -60);
    lv_obj_set_y(ui_Checkbox_Sett, -53);
    lv_obj_set_align(ui_Checkbox_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox_Sett, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Checkbox_Sett, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Checkbox_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_Checkbox_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Checkbox_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Checkbox_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Checkbox_Sett, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_Dropdown_Sett = lv_dropdown_create(ui_Settings_scroll_panel);
    lv_dropdown_set_options(ui_Dropdown_Sett, "Byte-Lab\nByteLab\nByte Lab\nBL");
    lv_obj_set_width(ui_Dropdown_Sett, 262);
    lv_obj_set_height(ui_Dropdown_Sett, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown_Sett, -8);
    lv_obj_set_y(ui_Dropdown_Sett, -15);
    lv_obj_set_align(ui_Dropdown_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown_Sett, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown_Sett, lv_color_hex(0x6AC6A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown_Sett, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Roller_Sett = lv_roller_create(ui_Settings_scroll_panel);
    lv_roller_set_options(ui_Roller_Sett, "Byte-Lab\nByteLab\nByte Lab\nBL", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller_Sett, 100);
    lv_obj_set_width(ui_Roller_Sett, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Roller_Sett, -93);
    lv_obj_set_y(ui_Roller_Sett, 64);
    lv_obj_set_align(ui_Roller_Sett, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller_Sett, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_Sett, lv_color_hex(0x101010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller_Sett, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller_Sett, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller_Sett, lv_color_hex(0x6AC6A4), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller_Sett, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slider1_Sett = lv_slider_create(ui_Settings_scroll_panel);
    lv_slider_set_range(ui_Slider1_Sett, 0, 20);
    lv_slider_set_value(ui_Slider1_Sett, 11, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1_Sett) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1_Sett, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1_Sett, 150);
    lv_obj_set_height(ui_Slider1_Sett, 10);
    lv_obj_set_x(ui_Slider1_Sett, 45);
    lv_obj_set_y(ui_Slider1_Sett, 25);
    lv_obj_set_align(ui_Slider1_Sett, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1_Sett, lv_color_hex(0xA1AAAD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1_Sett, lv_color_hex(0x6AC6A4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1_Sett, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Text_area = lv_textarea_create(ui_Settings_scroll_panel);
    lv_obj_set_width(ui_Text_area, 167);
    lv_obj_set_height(ui_Text_area, LV_SIZE_CONTENT);    /// 75
    lv_obj_set_x(ui_Text_area, -56);
    lv_obj_set_y(ui_Text_area, 145);
    lv_obj_set_align(ui_Text_area, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Text_area, "Type text here...");
    lv_textarea_set_one_line(ui_Text_area, true);



    ui_Arc_Sett = lv_arc_create(ui_Settings_scroll_panel);
    lv_obj_set_width(ui_Arc_Sett, 89);
    lv_obj_set_height(ui_Arc_Sett, 86);
    lv_obj_set_x(ui_Arc_Sett, 81);
    lv_obj_set_y(ui_Arc_Sett, 132);
    lv_obj_set_align(ui_Arc_Sett, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc_Sett, 89);
    lv_obj_set_style_arc_color(ui_Arc_Sett, lv_color_hex(0xA4AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Arc_Sett, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc_Sett, lv_color_hex(0x6AC6A4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc_Sett, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Slider2_Sett = lv_slider_create(ui_Settings_scroll_panel);
    lv_slider_set_value(ui_Slider2_Sett, 11, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2_Sett) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2_Sett, 1,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2_Sett, 150);
    lv_obj_set_height(ui_Slider2_Sett, 10);
    lv_obj_set_x(ui_Slider2_Sett, 45);
    lv_obj_set_y(ui_Slider2_Sett, 66);
    lv_obj_set_align(ui_Slider2_Sett, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2_Sett, lv_color_hex(0xA4AAAC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2_Sett, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2_Sett, lv_color_hex(0x6AC6A4), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2_Sett, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2_Sett, lv_color_hex(0x6AC6A4), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2_Sett, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Keyboard_Sett = lv_keyboard_create(ui_Settings_scroll_panel);
    lv_obj_set_width(ui_Keyboard_Sett, 273);
    lv_obj_set_height(ui_Keyboard_Sett, 119);
    lv_obj_set_x(ui_Keyboard_Sett, 0);
    lv_obj_set_y(ui_Keyboard_Sett, 233);
    lv_obj_set_align(ui_Keyboard_Sett, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard_Sett, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_Dark_Mode_Switch_Sett, ui_event_Dark_Mode_Switch_Sett, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Home_Btn_Sett, ui_event_Home_Btn_Sett, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Text_area, ui_event_Text_area, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard_Sett, ui_Text_area);
    lv_obj_add_event_cb(ui_Keyboard_Sett, ui_event_Keyboard_Sett, LV_EVENT_ALL, NULL);

}
